#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SaveBill.Resource", IsApplication=true)]

namespace SaveBill
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icone_conf = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icone_desenvolvedor = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icone_economia_agua = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icone_energia = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icone_graficos = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icone_hidrometro = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icone_leitura = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int btContaAgua = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int btContaLuz = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int btCreditos = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int btEstatistica = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int btLeitura = 2131099673;
			
			// aapt resource value: 0x7f06001c
			public const int btMetaMes = 2131099676;
			
			// aapt resource value: 0x7f060012
			public const int btModoEconomia = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int btSalvarLeitura = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int btSelecDist = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int btValorAtual = 2131099674;
			
			// aapt resource value: 0x7f060008
			public const int dialogo_beneficio = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int imageView1 = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int layCreditos = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int layLeitura = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int layMetaMes = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int layPrincipal = 2131099671;
			
			// aapt resource value: 0x7f060000
			public const int layValorAtual = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout2 = 2131099660;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout3 = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayout4 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout5 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout6 = 2131099679;
			
			// aapt resource value: 0x7f060016
			public const int listUltimasLeituras = 2131099670;
			
			// aapt resource value: 0x7f060023
			public const int menu_beneficio = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int menu_dist = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int menu_sair = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int menu_zerar = 2131099685;
			
			// aapt resource value: 0x7f06000f
			public const int pvGraficos = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int spBeneficio = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int spDistribuidora = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int textValorAtual = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textView3 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textView4 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int textView5 = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int txLeitura = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int txMetaMes = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int conta_atual = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int creditos = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialogo_beneficio = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int distribuidora = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int estatistica_uso = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int modo_economia = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int pega_leitura = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int principal = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int selecao_servico = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_principal = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
